tap "achannarasappa/tap"
tap "eranif/codelite"
tap "homebrew-ffmpeg/ffmpeg"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "kreuzwerker/taps"
tap "romkatv/powerlevel10k"
tap "teamookla/speedtest"
brew "libpng"
brew "libtiff"
brew "webp"
brew "atuin"
brew "autossh"
brew "gettext"
brew "awscli"
brew "bats-core"
brew "boost"
brew "bottom"
brew "pcre2"
brew "glib"
brew "gcc"
brew "libomp"
brew "clang-format"
brew "cloc"
brew "cmake"
brew "cookiecutter"
brew "ddcctl"
brew "difftastic"
brew "docker"
brew "fd"
brew "libarchive"
brew "librist"
brew "sdl2"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnuplot"
brew "gping"
brew "grep"
brew "pkg-config"
brew "htop"
brew "httpie"
brew "iperf3"
brew "ipython"
brew "jpeg"
brew "llvm"
brew "macchina"
brew "mackup"
brew "mas"
brew "ninja"
brew "meson"
brew "miniserve"
brew "nim"
brew "node"
brew "onefetch"
brew "opencv"
brew "perl"
brew "pipx"
brew "powerlevel10k"
brew "procs"
brew "ripgrep"
brew "sdl2_gfx"
brew "sdl2_image"
brew "sdl2_mixer"
brew "sdl2_net"
brew "sdl2_ttf"
brew "sdl_ttf"
brew "sfml"
brew "sloccount"
brew "speedtest-cli", link: false
brew "tealdeer"
brew "terraform"
brew "terragrunt"
brew "thefuck"
brew "tmux"
brew "tokei"
brew "tree"
brew "trippy"
brew "vim"
brew "wget"
brew "wireguard-tools"
brew "xh"
brew "ykman"
brew "youtube-dl"
brew "yt-dlp"
brew "zsh"
brew "achannarasappa/tap/ticker"
brew "kreuzwerker/taps/m1-terraform-provider-helper"
brew "teamookla/speedtest/speedtest"
cask "1password"
cask "font-hack-nerd-font"
cask "github"
cask "sloth"
mas "1Password for Safari", id: 1569813296
mas "AdBlock", id: 1402042596
mas "AdBlock Pro", id: 1018301773
mas "DaisyDisk", id: 411643860
mas "Dato", id: 1470584107
mas "Droplr", id: 498672703
mas "Flycut", id: 442160987
mas "Hand Mirror", id: 1502839586
mas "HP Easy Scan", id: 967004861
mas "HP Smart", id: 1474276998
mas "Kindle", id: 302584613
mas "PDF Expert", id: 1055273043
mas "Portal", id: 1436994560
mas "Quiver", id: 866773894
mas "Save to Pocket", id: 1477385213
mas "Super Agent", id: 1568262835
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "UpNote", id: 1398373917
mas "‎WhatsApp", id: 310633997
